name: Test Runner

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: docker
    steps:
      - uses: actions/checkout@v3

      - name: Say hi
        run: echo "DrewLive Forgejo Runner is WORKING 🚀"
